// scripts/seed.ts
// Run with: npx tsx scripts/seed.ts
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import ws from 'ws'

dotenv.config({ path: '.env.development' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,  // admin key to bypass RLS
  {
    realtime: { transport: ws as unknown as typeof WebSocket },
  }
)

const jobs = [
  {
    title: 'Senior Frontend Engineer',
    company: 'Razorpay',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2000000,
    salary_max: 3500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build high-performance React applications for our payments dashboard used by 8 million merchants. You will own the architecture of our merchant-facing web apps, work closely with product and design, and lead performance initiatives. We care deeply about Core Web Vitals and sub-second load times.',
    skills: ['React', 'TypeScript', 'Redux', 'Webpack', 'Performance', 'Jest'],
    apply_url: 'https://razorpay.com/jobs',
  },
  {
    title: 'Full Stack Engineer',
    company: 'Zepto',
    location: 'Mumbai',
    type: 'hybrid',
    salary_min: 1800000,
    salary_max: 3000000,
    currency: 'INR',
    experience: '3-6',
    description: 'Join our fast-growing team to build the technology behind 10-minute grocery delivery. Work on Next.js storefronts, Node.js microservices, and real-time order tracking systems. High scale, high impact — we process thousands of orders per minute.',
    skills: ['Next.js', 'Node.js', 'TypeScript', 'Redis', 'PostgreSQL', 'Docker'],
    apply_url: 'https://www.zeptonow.com/careers',
  },
  {
    title: 'React Native Developer',
    company: 'CRED',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2200000,
    salary_max: 3800000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the CRED mobile app used by 12 million premium credit card users. You will work on complex animations, payment flows, and performance optimisation for both iOS and Android from a single codebase.',
    skills: ['React Native', 'TypeScript', 'Reanimated', 'Redux', 'Jest'],
    apply_url: 'https://cred.club/careers',
  },
  {
    title: 'Frontend Engineer',
    company: 'Groww',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1500000,
    salary_max: 2800000,
    currency: 'INR',
    experience: '1-3',
    description: 'Help 50 million Indians invest confidently. Build intuitive investment dashboards, stock screeners, and real-time market data UIs. Performance and accessibility are first-class concerns on our platform.',
    skills: ['React', 'TypeScript', 'GraphQL', 'D3.js', 'Tailwind CSS'],
    apply_url: 'https://groww.in/careers',
  },
  {
    title: 'Senior Software Engineer — Frontend',
    company: 'Atlassian',
    location: 'Bangalore',
    type: 'remote',
    salary_min: 3500000,
    salary_max: 6000000,
    currency: 'INR',
    experience: '6-10',
    description: 'Work on Jira, Confluence, or Trello — products used by millions of teams globally. You will contribute to our design system, improve editor performance, and mentor junior engineers. Fully remote with async-first culture.',
    skills: ['React', 'TypeScript', 'GraphQL', 'Design Systems', 'Accessibility'],
    apply_url: 'https://www.atlassian.com/company/careers',
  },
  {
    title: 'UI Engineer',
    company: 'Swiggy',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1600000,
    salary_max: 2800000,
    currency: 'INR',
    experience: '1-3',
    description: 'Own the Swiggy web experience for 90 million users. Build restaurant discovery pages, cart and checkout flows, and real-time order tracking UI. We A/B test constantly — you will own experiments from code to analysis.',
    skills: ['React', 'JavaScript', 'CSS', 'Performance', 'A/B Testing'],
    apply_url: 'https://bytes.swiggy.com/careers',
  },
  {
    title: 'Staff Frontend Engineer',
    company: 'Meesho',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 4000000,
    salary_max: 7000000,
    currency: 'INR',
    experience: '6-10',
    description: 'Lead the frontend platform team at India biggest social commerce company. Define architecture standards, build internal tooling, drive performance budgets across 10 product teams, and hire senior engineers.',
    skills: ['React', 'TypeScript', 'Micro-frontends', 'Webpack', 'System Design'],
    apply_url: 'https://meesho.io/careers',
  },
  {
    title: 'Frontend Developer',
    company: 'PhonePe',
    location: 'Bangalore',
    type: 'onsite',
    salary_min: 1400000,
    salary_max: 2500000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build fast, reliable payment experiences for 450 million PhonePe users. Work on PWA development, deep-linked flows, and offline-first architecture. Our app needs to work on 2G networks in tier-3 cities.',
    skills: ['React', 'PWA', 'Service Workers', 'TypeScript', 'Performance'],
    apply_url: 'https://www.phonepe.com/careers',
  },
  {
    title: 'Senior React Developer',
    company: 'Postman',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2800000,
    salary_max: 4500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the Postman API platform used by 30 million developers. Work on our Electron desktop app and web client, complex code editors, API request builders, and real-time collaboration features.',
    skills: ['React', 'TypeScript', 'Electron', 'CodeMirror', 'WebSockets'],
    apply_url: 'https://www.postman.com/company/careers',
  },
  {
    title: 'Frontend Engineer — Remote',
    company: 'Hasura',
    location: 'Remote',
    type: 'remote',
    salary_min: 2500000,
    salary_max: 4000000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the Hasura console — a complex React application for managing GraphQL APIs and databases. You will work on SQL query builders, schema visualisers, and permission management UIs. Open source contribution is encouraged.',
    skills: ['React', 'TypeScript', 'GraphQL', 'Redux', 'Jest', 'Cypress'],
    apply_url: 'https://hasura.io/careers',
  },
  {
    title: 'Angular Developer',
    company: 'Infosys',
    location: 'Pune',
    type: 'hybrid',
    salary_min: 900000,
    salary_max: 1600000,
    currency: 'INR',
    experience: '1-3',
    description: 'Work on enterprise Angular applications for global banking and insurance clients. Build reusable component libraries, integrate REST APIs, and ensure WCAG accessibility compliance.',
    skills: ['Angular', 'TypeScript', 'RxJS', 'NgRx', 'Jasmine'],
    apply_url: 'https://www.infosys.com/careers',
  },
  {
    title: 'Full Stack Developer',
    company: 'Freshworks',
    location: 'Chennai',
    type: 'hybrid',
    salary_min: 1500000,
    salary_max: 2600000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build Freshdesk and Freshsales — CRM and helpdesk SaaS products used by 60,000 businesses. Full stack role: React frontend plus Ruby on Rails backend. Strong emphasis on product thinking and customer empathy.',
    skills: ['React', 'Ruby on Rails', 'PostgreSQL', 'Redis', 'TypeScript'],
    apply_url: 'https://www.freshworks.com/company/careers',
  },
  {
    title: 'Senior Engineer — React',
    company: 'Browserstack',
    location: 'Mumbai',
    type: 'hybrid',
    salary_min: 2500000,
    salary_max: 4000000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build developer tools used by 50,000 companies including Microsoft and Twitter. Work on our test management platform, live testing UI, and SDK integrations. We care about DX as much as UX.',
    skills: ['React', 'TypeScript', 'Node.js', 'WebRTC', 'Jest'],
    apply_url: 'https://www.browserstack.com/careers',
  },
  {
    title: 'Frontend Engineer — AI Products',
    company: 'Sarvam AI',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2000000,
    salary_max: 3800000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the frontend for India first large language model company. Create streaming chat interfaces, voice AI integrations, and developer playground UIs. Work directly with AI researchers to make cutting-edge models accessible.',
    skills: ['React', 'Next.js', 'TypeScript', 'Streaming APIs', 'WebSockets'],
    apply_url: 'https://www.sarvam.ai/careers',
  },
  {
    title: 'React Developer — Remote First',
    company: 'Toggl',
    location: 'Remote',
    type: 'remote',
    salary_min: 2800000,
    salary_max: 4500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Work on Toggl Track — the most popular time tracking tool with 5 million users. Fully distributed team across 40 countries, async-first culture. Build clean, fast interfaces that developers actually love.',
    skills: ['React', 'TypeScript', 'MobX', 'Styled Components', 'Cypress'],
    apply_url: 'https://toggl.com/jobs',
  },
  {
    title: 'Vue.js Developer',
    company: 'CleverTap',
    location: 'Mumbai',
    type: 'hybrid',
    salary_min: 1400000,
    salary_max: 2600000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build our customer engagement SaaS platform dashboards using Vue.js. Create campaign builders, funnel analytics, and real-time notification UIs for enterprise marketing teams.',
    skills: ['Vue.js', 'TypeScript', 'Vuex', 'D3.js', 'REST APIs'],
    apply_url: 'https://clevertap.com/careers',
  },
  {
    title: 'Senior Full Stack Engineer',
    company: 'Jupiter Money',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2500000,
    salary_max: 4200000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the next generation neo-banking experience for millennials. Work on React web apps and Node.js APIs handling real money transactions. Security, reliability, and delightful UX are our north stars.',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Redis', 'AWS'],
    apply_url: 'https://jupiter.money/careers',
  },
  {
    title: 'Frontend Architect',
    company: 'Flipkart',
    location: 'Bangalore',
    type: 'onsite',
    salary_min: 5000000,
    salary_max: 9000000,
    currency: 'INR',
    experience: '10+',
    description: 'Define the frontend architecture strategy for India largest e-commerce platform. Lead a team of 20 engineers, drive adoption of micro-frontends, establish performance standards, and partner with product and design leadership.',
    skills: ['React', 'Micro-frontends', 'TypeScript', 'System Design', 'Leadership'],
    apply_url: 'https://www.flipkartcareers.com',
  },
  {
    title: 'JavaScript Developer',
    company: 'Zoho',
    location: 'Chennai',
    type: 'onsite',
    salary_min: 800000,
    salary_max: 1600000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build features for Zoho CRM and Zoho Books used by 80 million users. Strong JavaScript fundamentals required. You will work on a large codebase with 15+ years of history — refactoring and clean code matter here.',
    skills: ['JavaScript', 'React', 'CSS', 'REST APIs', 'SQL'],
    apply_url: 'https://careers.zohocorp.com',
  },
  {
    title: 'Senior Engineer — Design Systems',
    company: 'Myntra',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2800000,
    salary_max: 4800000,
    currency: 'INR',
    experience: '6-10',
    description: 'Own Myntra design system used by 50 engineers. Build accessible, themeable React components, write comprehensive documentation, and partner with design to create the source of truth for our visual language.',
    skills: ['React', 'TypeScript', 'Storybook', 'Accessibility', 'CSS', 'Design Tokens'],
    apply_url: 'https://careers.myntra.com',
  },
  {
    title: 'Next.js Developer',
    company: 'Ola Electric',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1800000,
    salary_max: 3200000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the Ola Electric website and customer portal for India fastest growing EV brand. Create server-rendered product pages, booking flows, and owner dashboards. SEO performance is critical.',
    skills: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Prisma', 'PostgreSQL'],
    apply_url: 'https://olaelectric.com/careers',
  },
  {
    title: 'React + Node Developer',
    company: 'MoEngage',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1600000,
    salary_max: 2800000,
    currency: 'INR',
    experience: '1-3',
    description: 'Join our marketing automation platform team. Build campaign management dashboards, real-time analytics, and customer journey builders. Full-stack role with React frontend and Node.js backend microservices.',
    skills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Kafka'],
    apply_url: 'https://www.moengage.com/careers',
  },
  {
    title: 'Senior Frontend — Fintech',
    company: 'Slice',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2000000,
    salary_max: 3500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the digital credit card experience for Gen Z. Work on React Native and React web, payment flows, EMI calculators, and spend analytics. Move fast — we ship 3 releases a week.',
    skills: ['React', 'React Native', 'TypeScript', 'Redux', 'Figma'],
    apply_url: 'https://www.sliceit.com/careers',
  },
  {
    title: 'Frontend Engineer — B2B SaaS',
    company: 'Chargebee',
    location: 'Chennai',
    type: 'remote',
    salary_min: 1800000,
    salary_max: 3200000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build subscription management interfaces for 6,500 SaaS businesses including Freshworks and Typeform. Complex billing logic, invoice UIs, and revenue analytics dashboards. Remote-friendly team.',
    skills: ['React', 'TypeScript', 'GraphQL', 'Ember.js', 'Jest'],
    apply_url: 'https://www.chargebee.com/careers',
  },
  {
    title: 'Software Engineer — Frontend',
    company: 'Darwinbox',
    location: 'Hyderabad',
    type: 'hybrid',
    salary_min: 1400000,
    salary_max: 2600000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build HR tech for 850+ enterprises. Create payroll dashboards, performance management tools, and employee self-service portals. React-heavy codebase with strong emphasis on UX quality.',
    skills: ['React', 'JavaScript', 'SCSS', 'REST APIs', 'Agile'],
    apply_url: 'https://darwinbox.com/careers',
  },
  {
    title: 'Lead Frontend Engineer',
    company: 'Khatabook',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 3000000,
    salary_max: 5000000,
    currency: 'INR',
    experience: '6-10',
    description: 'Lead frontend for India largest digital ledger app used by 10 million small business owners. Own the web platform, mentor 5 engineers, and drive the migration from legacy codebase to modern React architecture.',
    skills: ['React', 'TypeScript', 'Redux', 'PWA', 'Performance', 'Mentoring'],
    apply_url: 'https://khatabook.com/careers',
  },
  {
    title: 'SDE-2 Frontend',
    company: 'Amazon',
    location: 'Hyderabad',
    type: 'onsite',
    salary_min: 3000000,
    salary_max: 5500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Join Amazon India consumer team building shopping experiences for 300 million customers. Contribute to product detail pages, search results, and checkout at massive scale. Strong CS fundamentals required.',
    skills: ['React', 'TypeScript', 'Java', 'AWS', 'Data Structures', 'Algorithms'],
    apply_url: 'https://amazon.jobs',
  },
  {
    title: 'Frontend Engineer — Open Source',
    company: 'Appsmith',
    location: 'Remote',
    type: 'remote',
    salary_min: 2200000,
    salary_max: 3800000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build Appsmith — the most popular open source low-code platform with 28,000 GitHub stars. Work on drag-and-drop builders, query editors, and widget libraries used by 10,000 companies. Your code is public.',
    skills: ['React', 'TypeScript', 'Redux', 'Styled Components', 'Open Source'],
    apply_url: 'https://www.appsmith.com/careers',
  },
  {
    title: 'Frontend + AI Integration Engineer',
    company: 'Fractal Analytics',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2000000,
    salary_max: 3500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build AI-powered analytics dashboards for Fortune 500 clients. Integrate LLM APIs into business intelligence tools, create natural language query interfaces, and visualise ML model outputs.',
    skills: ['React', 'Python', 'TypeScript', 'D3.js', 'OpenAI API', 'LLMs'],
    apply_url: 'https://fractal.ai/careers',
  },
  {
    title: 'React Developer — Healthcare',
    company: 'Practo',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1400000,
    salary_max: 2500000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build healthcare software used by 200,000 doctors and 200 million patients. Create appointment booking flows, teleconsultation UIs, and medical records management. Reliability and privacy are non-negotiable.',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'HIPAA'],
    apply_url: 'https://practo.com/careers',
  },
  {
    title: 'Senior Engineer — Platform',
    company: 'Wingify (VWO)',
    location: 'Delhi',
    type: 'hybrid',
    salary_min: 2200000,
    salary_max: 3800000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build VWO — the leading A/B testing and CRO platform. Work on the visual editor, heatmaps, and experimentation dashboards. Your code runs as a snippet on 10,000 websites — performance is everything.',
    skills: ['JavaScript', 'React', 'TypeScript', 'Performance', 'Browser APIs'],
    apply_url: 'https://wingify.com/careers',
  },
  {
    title: 'UI/UX Engineer',
    company: 'Unacademy',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1600000,
    salary_max: 2800000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build EdTech experiences for 50 million learners. Create live class interfaces, doubt-solving flows, and personalised study dashboards. Work closely with designers — pixel-perfect implementation matters.',
    skills: ['React', 'TypeScript', 'CSS', 'WebRTC', 'Animation'],
    apply_url: 'https://unacademy.com/careers',
  },
  {
    title: 'Frontend Engineer — Remote India',
    company: 'Sprinklr',
    location: 'Remote',
    type: 'remote',
    salary_min: 2500000,
    salary_max: 4000000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build unified customer experience management platform for enterprise clients. Complex React dashboards, social media management tools, and AI-powered content suggestion interfaces.',
    skills: ['React', 'TypeScript', 'Redux', 'GraphQL', 'Micro-frontends'],
    apply_url: 'https://www.sprinklr.com/careers',
  },
  {
    title: 'SDE-1 Frontend',
    company: 'ShareChat',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1200000,
    salary_max: 2200000,
    currency: 'INR',
    experience: 'fresher',
    description: 'Join Indias largest regional social media platform. Build short video features, creator studio tools, and content discovery feeds for 400 million users. Great place to grow as a new engineer.',
    skills: ['React', 'JavaScript', 'CSS', 'REST APIs', 'Git'],
    apply_url: 'https://careers.sharechat.com',
  },
  {
    title: 'TypeScript Engineer',
    company: 'Lenskart',
    location: 'Delhi',
    type: 'hybrid',
    salary_min: 1600000,
    salary_max: 2800000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build eyewear try-on and e-commerce experiences for 15 million Lenskart customers. Work on 3D virtual try-on features, prescription upload flows, and omnichannel checkout.',
    skills: ['TypeScript', 'React', 'Three.js', 'Node.js', 'MongoDB'],
    apply_url: 'https://lenskart.com/careers',
  },
  {
    title: 'Senior React + Redux Developer',
    company: 'Navi Technologies',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2200000,
    salary_max: 3600000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build lending and insurance products for 3 million Navi customers. Create loan application flows, insurance comparison tools, and portfolio management dashboards with strong emphasis on conversion optimization.',
    skills: ['React', 'Redux', 'TypeScript', 'Node.js', 'AWS', 'Fintech'],
    apply_url: 'https://navi.com/careers',
  },
  {
    title: 'Principal Frontend Engineer',
    company: 'InMobi',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 4500000,
    salary_max: 8000000,
    currency: 'INR',
    experience: '10+',
    description: 'Lead frontend engineering for InMobi advertising platform — one of the largest mobile ad networks globally. Define engineering culture, hire senior talent, and drive technical strategy for a team of 30.',
    skills: ['React', 'TypeScript', 'System Design', 'Leadership', 'Performance'],
    apply_url: 'https://www.inmobi.com/company/careers',
  },
  {
    title: 'Frontend Dev — Startup',
    company: 'Dukaan',
    location: 'Bangalore',
    type: 'remote',
    salary_min: 1400000,
    salary_max: 2500000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build the Dukaan platform that helps 7 million merchants create online stores without coding. Create drag-and-drop store builders, theme editors, and seller analytics. Small team, huge impact.',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Node.js'],
    apply_url: 'https://mydukaan.io/careers',
  },
  {
    title: 'Engineer — Web3 Frontend',
    company: 'CoinDCX',
    location: 'Mumbai',
    type: 'hybrid',
    salary_min: 2000000,
    salary_max: 3800000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build crypto trading and investment interfaces for 15 million CoinDCX users. Create real-time order books, candlestick charts, and portfolio tracking tools. Web3 wallet integration experience is a bonus.',
    skills: ['React', 'TypeScript', 'WebSockets', 'D3.js', 'Web3.js'],
    apply_url: 'https://coindcx.com/careers',
  },
  {
    title: 'React Developer — EdTech',
    company: 'BYJU S',
    location: 'Bangalore',
    type: 'onsite',
    salary_min: 1200000,
    salary_max: 2200000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build learning experiences for 150 million students. Create interactive lesson players, quiz engines, and gamification features. Work at scale — even small optimisations impact millions of daily active learners.',
    skills: ['React', 'JavaScript', 'Canvas API', 'Video.js', 'CSS Animations'],
    apply_url: 'https://byjus.com/careers',
  },
  {
    title: 'Senior Frontend — Remote',
    company: 'Multiplier',
    location: 'Remote',
    type: 'remote',
    salary_min: 2800000,
    salary_max: 5000000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build global employment and payroll SaaS for companies hiring across 150 countries. Complex multi-currency dashboards, contractor management, and compliance workflows. Fully remote, global team.',
    skills: ['React', 'TypeScript', 'GraphQL', 'Tailwind CSS', 'Cypress'],
    apply_url: 'https://www.usemultiplier.com/careers',
  },
  {
    title: 'Frontend Engineer — DevTools',
    company: 'Codecrafters',
    location: 'Remote',
    type: 'remote',
    salary_min: 3000000,
    salary_max: 5500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the most interesting developer education platform. Create terminal emulators in the browser, code execution interfaces, and real-time collaboration tools for engineers learning by building Redis, Git, and Docker from scratch.',
    skills: ['React', 'TypeScript', 'WebSockets', 'Xterm.js', 'Docker'],
    apply_url: 'https://codecrafters.io/careers',
  },
  {
    title: 'SDE-2 — React + AWS',
    company: 'Walmart Global Tech',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2800000,
    salary_max: 5000000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build e-commerce and supply chain tools for one of the world\'s largest retail companies. Work on seller portals, inventory management dashboards, and global order tracking. Strong system design expectations.',
    skills: ['React', 'TypeScript', 'AWS', 'Node.js', 'Microservices'],
    apply_url: 'https://careers.walmart.com',
  },
  {
    title: 'Software Engineer — Growth',
    company: 'Dream11',
    location: 'Mumbai',
    type: 'hybrid',
    salary_min: 2000000,
    salary_max: 3600000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build growth and engagement features for India largest fantasy sports platform. Own referral flows, onboarding experiments, push notification UIs, and gamification systems for 150 million users.',
    skills: ['React', 'TypeScript', 'Node.js', 'Redis', 'A/B Testing'],
    apply_url: 'https://dream11.com/careers',
  },
  {
    title: 'Frontend Developer — SaaS',
    company: 'Leadsquared',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1200000,
    salary_max: 2200000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build CRM and marketing automation software for education and financial services verticals. Create lead management pipelines, email campaign builders, and sales analytics dashboards.',
    skills: ['React', 'JavaScript', 'SCSS', 'REST APIs', 'Agile', 'Jest'],
    apply_url: 'https://www.leadsquared.com/careers',
  },
  {
    title: 'Senior UI Engineer — AI',
    company: 'Krutrim',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 2500000,
    salary_max: 4500000,
    currency: 'INR',
    experience: '3-6',
    description: 'Build the face of India first homegrown AI model. Create streaming chat interfaces, voice input UIs, multimodal interaction patterns, and developer playground tools. Ground-floor opportunity at a heavily-funded AI startup.',
    skills: ['React', 'Next.js', 'TypeScript', 'Streaming', 'WebSockets', 'LLMs'],
    apply_url: 'https://olakrutrim.com/careers',
  },
  {
    title: 'Platform Engineer — Frontend',
    company: 'Juspay',
    location: 'Bangalore',
    type: 'hybrid',
    salary_min: 1800000,
    salary_max: 3200000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build payments infrastructure used by Amazon, Flipkart, and Swiggy. Work on checkout SDKs, payment method UIs, and developer-facing dashboards. Your code processes $50 billion in payments annually.',
    skills: ['React', 'PureScript', 'TypeScript', 'Node.js', 'Payment APIs'],
    apply_url: 'https://juspay.in/careers',
  },
  {
    title: 'Frontend Engineer — Consumer',
    company: 'Nykaa',
    location: 'Mumbai',
    type: 'hybrid',
    salary_min: 1400000,
    salary_max: 2600000,
    currency: 'INR',
    experience: '1-3',
    description: 'Build fashion and beauty e-commerce experiences for 35 million Nykaa shoppers. Own product discovery pages, virtual try-on features, and personalised recommendation UIs.',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'CSS'],
    apply_url: 'https://careers.nykaa.com',
  },
]

async function seed() {
  console.log(`Seeding ${jobs.length} jobs...`)

  const rows = jobs.map(({ title, company, location, type, salary_min, salary_max, description, skills }) => ({
    title,
    company,
    location,
    type,
    salary_min,
    salary_max,
    description,
    skills,
  }))

  const { data, error } = await supabase
    .from('jobs')
    .insert(rows)
    .select('id, title')

  if (error) {
    console.error('Seed failed:', error.message)
    process.exit(1)
  }

  console.log(`✓ Inserted ${data.length} jobs successfully`)
  data.forEach(j => console.log(`  · ${j.title}`))
}

seed()